# this file contains the parameters used to fill in the drop-down menus of the character generator interface

# by default the selected item will be set to none
NONE_STRING = "-----"

GENDER_LIST = [NONE_STRING,
              "Male", "Female"
]

RACES_LIST = [NONE_STRING,
                "Andorian",
                "Avian",
                "Bajoran",
                "Betazoid",
                "Borg",
                "Cardassian",
                "Dracthyr",
                "Draenei",
                "Dragonborn",
                "Dwarf",
                "Elf",
                "Ewok",
                "Ferengi",
                "Forsaken",
                "Gnome",
                "Goblin",
                "Halfling",
                "Human",
                "Insectoid",
                "Klingon",
                "Nightborne",
                "Orc",
                "Pandaren",
                "Reptilian",
                "Romulan",
                "Sith",
                "Talaxian",
                "Tauren",
                "Tiefling",
                "Troll",
                "Vampire",
                "Vulcan",
                "Vulpera",
                "Worgen",
                "Xindi",
                "Yeti",
]

# color names based on X11 norm
# source https://www.w3.org/TR/css-color-3/#svg-color
COLORS_LIST = [NONE_STRING,
               "Aquamarine",
               "Azure",
               "Beige",
               "Black",
               "Blue",
               "Brown",
               "Burlywood",
               "Chartreuse",
               "Coral",
               "Cornsilk",
               "Crimson",
               "Cyan",
               "Fuchsia",
               "Gold",
               "Goldenrod",
               "Gray",
               "Green",
               "Honeydew",
               "Indigo",
               "Ivory",
               "Khaki",
               "Lavender",
               "Lime",
               "Maroon",
               "Navy",
               "Olive",
               "Orange",
               "Orchid",
               "Pink",
               "Plum",
               "Purple",
               "Red",
               "Salmon",
               "Sienna",
               "Silver",
               "Teal",
               "Tomato",
               "Turquoise",
               "Violet",
               "Wheat",
               "White",
               "Yellow",
               ]

BODY_TYPES_LIST = [NONE_STRING,
                    "athletic",
                    "brawny",
                    "buxom",
                    "chubby",
                    "curvy",
                    "gangly",
                    "lanky",
                    "lean",
                    "lithe",
                    "muscular",
                    "petite",
                    "plump",
                    "portly",
                    "sinewy",
                    "skinny",
                    "slim",
                    "stocky",
                    "stout",
                    "voluptuous",
                    "willowy",
                   ]

SKIN_LIST = [NONE_STRING,
                "cracked",
                "dry",
                "flushed",
                "freckled",
                "pale",
                "scarred",
                "shiny",
                "silky",
                "sunburned",
                "sweaty",
                "tan",
                "tattooed",
                "tiger-like",
                "wet",
             ]

HAIR_TYPES_LIST = [NONE_STRING,
                    "afro",
                    "asymmetrical",
                    "beehive",
                    "bob cut",
                    "braid",
                    "braided crown",
                    "bun",
                    "cornrows",
                    "crew cut",
                    "dreadlocks",
                    "fade",
                    "layered cut",
                    "mohawk",
                    "pixie cut",
                    "pompadour",
                    "ponytail",
                    "quiff",
                    "shag",
                    "slicked back",
                    "top knot",
                    "undercut",
                   ]