# this file contains the parameters used to fill in the drop-down menus of the character generator interface

# by default the selected item will be set to none
NONE_STRING = "-----"

COMMON_PROMPT_ENDING = ("full body, dynamic pose, life size, perfect anatomy, detailed skin texture, full HD, 4K, HDR, "
                        "depth of field.")

GENDER_LIST = [NONE_STRING,
               "Male", "Female"
               ]

SCENES_LIST = [NONE_STRING,
               "Antiquity",
               "DC Comics",
               "Dungeons and Dragons",
               "Futuristic",
               "Golden Age",
               "Middle Ages",
               "Modern Era",
               "Prehistoric",
               "Renaissance",
               "Star Trek",
               "Star Wars",
               "World of Warcraft",
               ]

RACES_LIST = [NONE_STRING,
              "Andorian",
              "Avian",
              "Bajoran",
              "Betazoid",
              "Borg",
              "Cardassian",
              "Dracthyr",
              "Draenei",
              "Dragonborn",
              "Dwarf",
              "Elf",
              "Ewok",
              "Ferengi",
              "Forsaken",
              "Gnome",
              "Goblin",
              "Halfling",
              "Human",
              "Insectoid",
              "Klingon",
              "Nightborne",
              "Orc",
              "Pandaren",
              "Reptilian",
              "Romulan",
              "Sith",
              "Talaxian",
              "Tauren",
              "Tiefling",
              "Troll",
              "Vampire",
              "Vulcan",
              "Vulpera",
              "Worgen",
              "Xindi",
              "Yeti",
              ]

# color names based on X11 norm
# source https://www.w3.org/TR/css-color-3/#svg-color
COLORS_LIST = [NONE_STRING,
               "Aquamarine",
               "Azure",
               "Beige",
               "Black",
               "Blue",
               "Brown",
               "Burlywood",
               "Chartreuse",
               "Coral",
               "Cornsilk",
               "Crimson",
               "Cyan",
               "Fuchsia",
               "Gold",
               "Goldenrod",
               "Gray",
               "Green",
               "Honeydew",
               "Indigo",
               "Ivory",
               "Khaki",
               "Lavender",
               "Lime",
               "Maroon",
               "Navy",
               "Olive",
               "Orange",
               "Orchid",
               "Pink",
               "Plum",
               "Purple",
               "Red",
               "Salmon",
               "Sienna",
               "Silver",
               "Teal",
               "Tomato",
               "Turquoise",
               "Violet",
               "Wheat",
               "White",
               "Yellow",
               ]

BODY_TYPES_LIST = [NONE_STRING,
                   "athletic",
                   "brawny",
                   "buxom",
                   "chubby",
                   "curvy",
                   "gangly",
                   "lanky",
                   "lean",
                   "lithe",
                   "muscular",
                   "petite",
                   "plump",
                   "portly",
                   "sinewy",
                   "skinny",
                   "slim",
                   "stocky",
                   "stout",
                   "voluptuous",
                   "willowy",
                   ]

SKIN_LIST = [NONE_STRING,
             "cracked",
             "dry",
             "flushed",
             "freckled",
             "pale",
             "scarred",
             "shiny",
             "silky",
             "sunburned",
             "sweaty",
             "tan",
             "tattooed",
             "tiger-like",
             "wet",
             ]

HAIR_TYPES_LIST = [NONE_STRING,
                   "afro",
                   "asymmetrical",
                   "beehive",
                   "bob cut",
                   "braid",
                   "braided crown",
                   "bun",
                   "cornrows",
                   "crew cut",
                   "dreadlocks",
                   "fade",
                   "layered cut",
                   "mohawk",
                   "pixie cut",
                   "pompadour",
                   "ponytail",
                   "quiff",
                   "shag",
                   "slicked back",
                   "top knot",
                   "undercut",
                   ]

CLOTHING_MATERIAL_LIST = [NONE_STRING,
                          "bronze",
                          "canvas",
                          "chainmail",
                          "copper",
                          "cotton",
                          "ether",
                          "fur",
                          "gold",
                          "leather",
                          "linen",
                          "mesh",
                          "mithril",
                          "nylon",
                          "platinum",
                          "polyester",
                          "rubber",
                          "satin",
                          "silk",
                          "silver",
                          "steel",
                          "velvet",
                          "wool",
                          ]

CLOTHING_TYPE_LIST = [NONE_STRING,
                      "blazer",
                      "cape",
                      "chainmail",
                      "cloak",
                      "coat",
                      "doublet",
                      "dress",
                      "gambeson",
                      "hauberk",
                      "jacket",
                      "jerkin",
                      "loincloth",
                      "longyi",
                      "mantle",
                      "parka",
                      "peacoat",
                      "poncho",
                      "robe",
                      "sarong",
                      "shawl",
                      "shirt",
                      "skirt",
                      "spacesuit",
                      "sportswear",
                      "surcoat",
                      "swimwear",
                      "tabard",
                      "toga",
                      "tunic",
                      "vest",
                      "windbreaker",
                      "wrap",
                      ]

TOOLS_LIST = [NONE_STRING,
              "amulet",
              "axe",
              "book",
              "bow",
              "chalice",
              "club",
              "crystal",
              "cup",
              "dagger",
              "drum",
              "flail",
              "flute",
              "gong",
              "halberd",
              "hammer",
              "harp",
              "lightsaber",
              "lyre",
              "mace",
              "mandolin",
              "manuscript",
              "medallion",
              "morningstar",
              "pike",
              "scimitar",
              "smartphone",
              "spear",
              "staff",
              "sword",
              "trident",
              "violin",
              "whip",
              ]

TOOL_ACTIONS_LIST = [NONE_STRING,
                     "catching",
                     "discarding",
                     "holding",
                     "looking at",
                     "parrying",
                     "picking up",
                     "playing",
                     "preparing",
                     "swinging",
                     "throwing",
                     "thrusting",
                     "using",
                     ]

ACTIVITY_LIST = [NONE_STRING,
                 "Drinking",
                 "Eating",
                 "Fighting",
                 "Jumping",
                 "Meditating",
                 "Praying",
                 "Reading",
                 "Running",
                 "Sitting",
                 "Sleeping",
                 "Standing",
                 "Thinking",
                 "Walking",
                 "Watching",
                 ]

POSES_LIST = [NONE_STRING,
              "Abstracted Body",
              "Adlocutio",
              "Anamorphic Perspective",
              "Anjali Mudra",
              "Automatist",
              "Bodhisattva",
              "Contrapposto",
              "Dynamic",
              "Ecce Homo",
              "Gamelan Dance",
              "Javanese Royal",
              "Laocoön",
              "Lotus",
              "Nataraja",
              "Nihonga Portrait",
              "Odalisque",
              "Orans",
              "Pieta",
              "Samurai Stance",
              "Sanqiao Shi",
              "Scholar",
              "Seated Chief",
              "Seiza",
              "Selfie",
              "Tribhanga",
              "Trikonasana",
              "Venus Pudica",
              "Vrikshasana",
              "Warrior",
              "Wayang Kulit",
              ]
