# this file contains the parameters used to fill in the drop-down menus of the user interface

# by default the selected item will be set to none
NONE_STRING = "-----"

STYLE_LIST = [NONE_STRING,
              "Abstract",
              "Baroque",
              "Classicism",
              "Cubism",
              "Dadaism",
              "Expressionism",
              "Flemish Masters",
              "Futurism",
              "Gothic",
              "Impressionism",
              "Medieval",
              "Minimalism",
              "Moorish",
              "Mughal",
              "Nihonga",
              "Orientalism",
              "Pop Art",
              "Realism",
              "Renaissance",
              "Rococo",
              "Romanesque",
              "Surrealism",]

# styles supported by Stable Diffusion
ART_TYPE_LIST = [NONE_STRING,
                 "acrylic painting",
                 "analytic drawing",
                 "anime",
                 "cartoon art",
                 "cinematographic scene",
                 "coloring book",
                 "concept art",
                 "dark fantasy",
                 "digital painting",
                 "dripping art",
                 "isometric illustration",
                 "Japanese ink art",
                 "light painting",
                 "lithograph",
                 "low-res pixel art",
                 "oil painting",
                 "one line drawing",
                 "paper cut craft illustration",
                 "paper quilling",
                 "pastel drawing",
                 "patchwork collage",
                 "photo",
                 "polaroid",
                 "portrait",
                 "product shot",
                 "serigraph",
                 "stained glass",
                 "typography art",
                 "ukiyo-e art",
                 "watercolor painting",
                 "woodcut"]

# specifying the camera angle gives more realistic images
CAMERA_ANGLE_LIST = [NONE_STRING,
                     "aerial view",
                     "close-up",
                     "Dutch angle",
                     "fish-eye lens",
                     "full body shot",
                     "long shot",
                     "low angle",
                     "mid shot",
                     "wide angle"]

# lights are an important aspect of both photography and painting
LIGHTING_LIST = [NONE_STRING,
                 "accent lighting",
                 "ambient lighting",
                 "backlight",
                 "blacklight",
                 "blue hour",
                 "candlelight",
                 "concert lighting",
                 "dusk",
                 "fluorescent",
                 "golden hour",
                 "natural lighting",
                 "moonlight",
                 "neon lamp",
                 "nighttime",
                 "Rembrandt lighting",
                 "rim lighting",
                 "soft lighting",
                 "strobe",
                 "sunlight",
                 "ultraviolet"]

# it is possible to adjust the color
COLOR_PALETTE_LIST = [NONE_STRING,
                      "black and white",
                      "monochrome",
                      "neon colors",
                      "pastel colors",
                      "polychromatic",
                      "saturated colors",
                      "vibrant colors"]

# a few additional commands to modify an image
ADDITIONAL_FEATURES_LIST = [NONE_STRING,
                            "4K",
                            "8K",
                            "detailed skin",
                            "HDR",
                            "hyper realistic",
                            "octane render",
                            "photorealistic"]

# some light effects to be played with for some surrealistic images
SPECIAL_EFFECTS_LIST = [NONE_STRING,
                        "aurora glimmer",
                        "bioluminescent",
                        "chemiluminescent",
                        "electricluminescent",
                        "electromagnetic pulse glow",
                        "fiber-optic weave",
                        "holographic flares",
                        "phosphorescent shimmer",
                        "thermoluminescent"
                        ]

COLOR_VIBES_LIST = [NONE_STRING,
                    "Celestial Harmony",
                    "Enchanted Forest",
                    "Sunset Serenity",
                    "Galactic Nebula",
                    "Cyberpunk Dream",
                    "Desert Mirage",
                    "Aurora Borealis",
                    "Retro Futurism",
                    "Tropical Bliss",
                    "Midnight Jazz",
]


COMPOSITIONS_LIST = [NONE_STRING,
                     "Rule of Thirds",
                     "Symmetrical",
                     "Leading Lines",
                     "Circular",
                     "Golden Ratio",
                     "Framing",
                     "Vertical",
                     "Horizontal",
                     "Negative Space",
                     "Contrast",
                     "Geometric Pattern",
                     "Intricate Pattern",

]
