# this file contains the parameters used to fill in the drop-down menus of the user interface

# by default the selected item will be set to none
NONE_STRING = "-----"

STYLE_LIST = [NONE_STRING,
              "Abstract",
              "Baroque",
              "Chibi",
              "Classicism",
              "Cubism",
              "Dadaism",
              "Expressionism",
              "Film Noir",
              "Flemish painting ",
              "Futurism",
              "Gothic",
              "Impressionism",
              "Medieval",
              "Minimalism",
              "Moorish",
              "Mughal",
              "Nihonga",
              "Orientalism",
              "Pop Art",
              "Realism",
              "Renaissance",
              "Rococo",
              "Romanesque",
              "Surrealism",]

# styles supported by Stable Diffusion
ART_TYPE_LIST = [NONE_STRING,
                 "acrylic painting",
                 "analytic drawing",
                 "anime",
                 "barcode artwork",
                 "biomorphism",
                 "botanical art",
                 "cartoon art",
                 "cinematographic scene",
                 "coloring book",
                 "concept art",
                 "dark fantasy",
                 "digital painting",
                 "dripping art",
                 "isometric illustration",
                 "Japanese ink art",
                 "light painting",
                 "lithograph",
                 "low-res pixel art",
                 "microbial art",
                 "oil painting",
                 "one line drawing",
                 "origami",
                 "paper cut craft illustration",
                 "paper quilling",
                 "pastel drawing",
                 "patchwork collage",
                 "photo",
                 "polaroid",
                 "portrait",
                 "product shot",
                 "serigraph",
                 "silverpoint",
                 "stained glass",
                 "typography art",
                 "ukiyo-e art",
                 "watercolor painting",
                 "woodcut"]

# specifying the camera angle gives more realistic images
CAMERA_ANGLE_LIST = [NONE_STRING,
                     "aerial view",
                     "close-up",
                     "Dutch angle",
                     "fish-eye lens",
                     "full body shot",
                     "long shot",
                     "low angle",
                     "mid shot",
                     "wide angle",
                     "worm view"]

# lights are an important aspect of both photography and painting
LIGHTING_LIST = [NONE_STRING,
                 "accent lighting",
                 "ambient lighting",
                 "backlight",
                 "blacklight",
                 "blue hour",
                 "candlelight",
                 "concert lighting",
                 "dusk",
                 "fluorescent",
                 "golden hour",
                 "infrared",
                 "natural lighting",
                 "moonlight",
                 "neon lamp",
                 "nighttime",
                 "Rembrandt lighting",
                 "rim lighting",
                 "soft lighting",
                 "strobe",
                 "sunlight",
                 "ultraviolet"]

# it is possible to adjust the color
COLOR_PALETTE_LIST = [NONE_STRING,
                      "black and white",
                      "monochrome",
                      "neon colors",
                      "pastel colors",
                      "polychromatic",
                      "saturated colors",
                      "vibrant colors"]

COLOR_VIBES_LIST = [NONE_STRING,
                    "Arctic Chill",
                    "Aurora Borealis",
                    "Autumn Splendor",
                    "Boho Beauty",
                    "Celestial Harmony",
                    "Cyberpunk Dream",
                    "Desert Mirage",
                    "Enchanted Forest",
                    "Galactic Nebula",
                    "Midnight Jazz",
                    "Misty Lavender",
                    "Neon Noir",
                    "Nomadic Earth",
                    "Oceanic Harmony",
                    "Pastel Punk",
                    "Regal Opulence",
                    "Retro Futurism",
                    "Spring Fling",
                    "Summer Aesthetic",
                    "Sunset Serenity",
                    "Synthwave Sunset",
                    "Teal Wave",
                    "Terracotta Accents",
                    "Tropical Bliss",
                    "Urban Elegance",
                    "Volcanic Twilight",
                    "Wanderlust Whimsy",
                    "Winter Wonderland",
                    "Zen Balance"]


COMPOSITIONS_LIST = [NONE_STRING,
                     "Circular",
                     "Contrast",
                     "Framing",
                     "Geometric Pattern",
                     "Golden Ratio",
                     "Horizontal",
                     "Intricate Pattern",
                     "Knollig",
                     "Leading Lines",
                     "Negative Space",
                     "Rule of Thirds",
                     "Symmetrical",
                     "Vertical",]

# some light effects to be played with for some surrealistic images
SPECIAL_EFFECTS_LIST = [NONE_STRING,
                        "aurora glimmer",
                        "bioluminescent",
                        "chemiluminescent",
                        "electricluminescent",
                        "electromagnetic pulse glow",
                        "fiber-optic weave",
                        "holographic flares",
                        "phosphorescent shimmer",
                        "thermoluminescent"]

# a few additional commands to modify an image
MISCELLANEOUS_LIST = [NONE_STRING,
                            "4K",
                            "8K",
                            "detailed skin",
                            "HDR",
                            "hyper realistic",
                            "masterpiece",
                            "octane render",
                            "photorealistic",
                            "trending on artstation"]
